export default [
  {
    Name: "Aryan Shridhar",
    Email: "aryanshridhar@gmail.com",
    Tasks: 10,
    CTasks: 4,
    Tasks_onTime: 9,
    CTasks_onTime: 3,
  },
  {
    Name: "Random Person",
    Email: "randomperson@gmail.com",
    Tasks: 5,
    CTasks: 2,
    Tasks_onTime: 4,
    CTasks_onTime: 1,
  },
  {
    Name: "Agniva Basak",
    Email: "agnivabasak1@gmail.com",
    Tasks: 9,
    CTasks: 2,
    Tasks_onTime: 5,
    CTasks_onTime: 2,
  },
  {
    Name: "Random Person",
    Email: "randomperson@gmail.com",
    Tasks: 2,
    CTasks: 1,
    Tasks_onTime: 2,
    CTasks_onTime: 1,
  },
  {
    Name: "Shobhit Gupta",
    Email: "shobhitgupta@gmail.com",
    Tasks: 7,
    CTasks: 3,
    Tasks_onTime: 7,
    CTasks_onTime: 1,
  },
  {
    Name: "Random Person",
    Email: "randomperson@gmail.com",
    Tasks: 6,
    CTasks: 5,
    Tasks_onTime: 5,
    CTasks_onTime: 3,
  },
  {
    Name: "Random Person",
    Email: "randomperson@gmail.com",
    Tasks: 1,
    CTasks: 2,
    Tasks_onTime: 1,
    CTasks_onTime: 2,
  },
];
